# Generated by Django 4.0.4 on 2022-05-23 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal_date', models.DateField()),
                ('time_spent', models.IntegerField()),
            ],
        ),
    ]
